/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex('products').insert([
    {
      id: 1,
      name: 'Iphone 14 Pro',
      price: 1999,
      description: `Experience the pinnacle of innovation with the Apple iPhone 14 Pro. Boasting a 6.7-inch Super Retina XDR display with ProMotion technology, it delivers breathtaking visuals. Powered by the A16 Bionic chip and 8GB of RAM, this device offers unmatched performance and smooth multitasking. Capture professional-quality photos and videos with the triple-camera system and take advantage of the LiDAR scanner for augmented reality experiences. Your data remains secure with Face ID, and the larger battery supports fast charging and wireless charging. With 5G connectivity and iOS 15, the iPhone 14 Pro is a testament to Apple's commitment to excellence.`,
      imageUrl: '/images/Iphone-14-Pro.jpeg',
      category_id: 1,
    },

    {
      id: 2,
      name: 'Macbook Pro 14inch M1',
      price: 3999,
      description: `Introducing the Apple MacBook Pro 14-inch M1, a powerhouse of productivity and creativity. With its sleek and lightweight design, this laptop is built to accompany you on-the-go. The M1 chip delivers blazing-fast performance and efficiency, enabling seamless multitasking and smooth graphics rendering. The 14-inch Retina display offers stunning visuals with vibrant colors and sharp details. The Magic Keyboard provides a comfortable typing experience, while the Touch Bar offers intuitive control. The MacBook Pro 14-inch M1 features a generous battery life, Thunderbolt ports for high-speed connectivity, and the macOS Big Sur operating system, making it the ultimate choice for professionals and enthusiasts alike.`,
      imageUrl: '/images/Macbook-Pro-14-M1.jpeg',
      category_id: 2,
    },
    {
      id: 3,
      name: 'Ipad Pro 11inch',
      price: 1999,
      description: `Introducing the Apple iPad Pro 11-inch, a versatile and powerful tablet that takes mobile computing to new heights. With its sleek and compact design, this iPad is perfect for both work and play. Powered by the M1 chip, it delivers lightning-fast performance and exceptional graphics capabilities. The 11-inch Liquid Retina display offers stunning visuals with true-to-life colors and ProMotion technology for smooth scrolling. With the Apple Pencil compatibility, you can unleash your creativity and take precise notes or create detailed artwork. The iPad Pro 11-inch boasts a high-quality camera system, Face ID for secure authentication, and all-day battery life. Whether you're a professional or a casual user, the iPad Pro 11-inch is your ultimate companion for productivity and entertainment.`,
      imageUrl: '/images/Ipad-Pro.jpeg',
      category_id: 3,
    },
    {
      id: 4,
      name: 'Airpods Pro',
      price: 500,
      description: `Introducing the Apple AirPods Pro, the ultimate wireless earbuds for an immersive audio experience. With their sleek and ergonomic design, these earbuds offer a comfortable fit and secure seal for exceptional sound quality. The active noise cancellation feature blocks out external distractions, allowing you to focus on your music, calls, or podcasts. The transparency mode lets you hear your surroundings when needed. The AirPods Pro deliver rich, detailed sound with powerful bass and crisp highs. They are also sweat and water-resistant, making them perfect for workouts and outdoor activities. With easy setup and seamless integration with Apple devices, the AirPods Pro are the perfect audio companion for any occasion.`,
      imageUrl: '/images/Airpod-Pro.jpeg',
      category_id: 4,
    },
    {
      id: 5,
      name: 'Cream',
      price: 1,
      description: `Meet Cream, the adorable feline companion with white fur and mesmerizing blue eyes. This lovable cat is a bundle of joy, always ready to offer warm cuddles and affectionate purrs. Cream's silky white fur not only adds to their irresistible charm but also makes them a true standout. With their captivating blue eyes, Cream has a gaze that can melt hearts and captivate anyone who meets them. Whether it's snuggling up for a cozy nap or playfully chasing toys, Cream is the perfect companion for companionship and endless love. Embrace the cuddly bliss that Cream brings into your life and experience the joy of having a delightful feline friend by your side.`,
      imageUrl: '/images/Cream.png',
      category_id: 5,
    },
    {
      id: 6,
      name: 'Iphone 14 Plus',
      price: 1799,
      description: `Introducing the iPhone 14 Plus, the epitome of innovation and elegance in the world of smartphones. With its larger display and cutting-edge features, this device takes your mobile experience to a whole new level. The iPhone 14 Plus boasts a generous 6.5-inch Super Retina XDR display, offering vibrant colors and stunning visuals. Powered by the latest A16 Bionic chip, it delivers unrivaled speed and efficiency for seamless performance. Capture your life's moments in breathtaking detail with the advanced camera system, while Face ID ensures top-notch security. Embrace the future with 5G connectivity, and enjoy the latest iOS features for an unparalleled user experience. The iPhone 14 Plus is a perfect blend of style and substance, making it the ideal choice for those seeking the best in technology and design.`,
      imageUrl: '/images/Iphone-14-Plus.jpeg',
      category_id: 1,
    },
    {
      id: 7,
      name: 'Iphone 14',
      price: 1599,
      description: `Introducing the iPhone 14, the next evolution in smartphone technology. With its sleek design and groundbreaking features, the iPhone 14 sets a new standard for innovation. Equipped with a stunning 6.1-inch Super Retina XDR display, this device delivers immersive visuals with vibrant colors and sharp details. Powered by the advanced A16 Bionic chip, it offers blazing-fast performance and enhanced efficiency for seamless multitasking. Capture professional-quality photos and videos with the improved camera system, and enjoy enhanced security with Face ID. Stay connected with lightning-fast 5G connectivity, and explore the latest iOS features that redefine the way you interact with your phone. The iPhone 14 is the epitome of excellence, combining cutting-edge technology with unmatched style.`,
      imageUrl: '/images/Iphone-14.jpeg',
      category_id: 1,
    },
    {
      id: 8,
      name: 'Iphone 13',
      price: 1399,
      description: `Introducing the iPhone 13, a device that takes smartphone technology to new heights. With its sleek and refined design, this iPhone is a true epitome of elegance. The 6.1-inch Super Retina XDR display showcases vibrant colors and incredible clarity, making every image and video come to life. Powered by the powerful A15 Bionic chip, the iPhone 13 offers exceptional performance, ensuring seamless multitasking and smooth gaming experiences. Capture stunning photos and videos with the advanced camera system, and enjoy enhanced low-light performance and improved image stabilization. With all-day battery life, Face ID for secure authentication, and 5G connectivity, the iPhone 13 is designed to keep up with your fast-paced lifestyle. Experience the next generation of smartphones with the iPhone 13 and elevate your mobile experience to a whole new level.`,
      imageUrl: '/images/Iphone-13.jpeg',
      category_id: 1,
    },
    {
      id: 9,
      name: 'MacBook Pro 13inch M1',
      price: 1399,
      description: `
      Introducing the MacBook Pro 13-inch M1, a powerhouse of productivity in a compact form factor. With its sleek and lightweight design, this laptop is built to accompany you wherever you go. The M1 chip delivers unprecedented performance and efficiency, enabling seamless multitasking and smooth graphics rendering. The 13-inch Retina display offers stunning visuals with vibrant colors and sharp details. The Magic Keyboard provides a comfortable typing experience, while the Touch Bar offers convenient shortcuts. The MacBook Pro 13-inch M1 features impressive battery life, Thunderbolt/USB 4 ports for high-speed connectivity, and the macOS Big Sur operating system. Experience blazing-fast speed and remarkable power with the MacBook Pro 13-inch M1, the ultimate tool for professionals and creatives.`,
      imageUrl: '/images/MacBook-Pro-13.jpeg',
      category_id: 2,
    },
    {
      id: 10,
      name: 'MacBook Air 13inch M1',
      price: 1699,
      description: `Introducing the MacBook Air 13-inch M1, the epitome of power and portability. This ultra-sleek and lightweight laptop is designed to revolutionize your computing experience. Powered by the groundbreaking M1 chip, it delivers lightning-fast performance, exceptional battery life, and incredible efficiency. The 13-inch Retina display offers stunning visuals with vibrant colors and sharp details. The Magic Keyboard provides a comfortable typing experience, while the Touch ID ensures secure and effortless authentication. With its fanless design, the MacBook Air 13-inch M1 operates silently and stays cool under heavy workloads. Thunderbolt/USB 4 ports enable fast data transfer and connection to external devices. Experience the future of laptops with the MacBook Air 13-inch M1, where power meets mobility.`,
      imageUrl: '/images/Macbook-Air-13-M1.webp',
      category_id: 2,
    },
    {
      id: 11,
      name: 'MacBook Air 13inch M2',
      price: 1399,
      description: `Introducing the MacBook Air 13-inch M2, a perfect blend of power and portability. This ultra-slim and lightweight laptop is designed to keep up with your on-the-go lifestyle. Powered by the advanced M2 chip, it delivers remarkable performance and efficiency, allowing you to breeze through tasks and enjoy smooth multitasking. The 13-inch Retina display offers stunning visuals with true-to-life colors and sharp details. The Magic Keyboard provides a comfortable typing experience, while the Touch ID ensures secure and convenient authentication. With long-lasting battery life, Thunderbolt/USB 4 ports for fast connectivity, and the macOS operating system, the MacBook Air 13-inch M2 is your ideal companion for work and play. Elevate your productivity and embrace the freedom of mobility with the MacBook Air 13-inch M2.`,
      imageUrl: '/images/Macbook-Air-13-M2.jpeg',
      category_id: 2,
    },
    {
      id: 12,
      name: 'Ipad 10.9inch',
      price: 899,
      description: `Introducing the iPad 10.9-inch, a versatile and immersive tablet that takes your digital experience to new heights. With its sleek design and stunning Liquid Retina display, this iPad offers a captivating visual experience with true-to-life colors and sharp details. Powered by the A14 Bionic chip, it delivers exceptional performance and responsiveness, making multitasking a breeze. The 10.9-inch size strikes the perfect balance between portability and productivity, allowing you to comfortably work, play, and create on the go. With Apple Pencil and Magic Keyboard compatibility, you can unleash your creativity and boost your productivity even further. Whether you're browsing the web, editing photos, or enjoying your favorite content, the iPad 10.9-inch is your ultimate companion for all your digital needs.`,
      imageUrl: '/images/Ipad.jpeg',
      category_id: 3,
    },
    {
      id: 13,
      name: 'Ipad Air 10.9inch',
      price: 1199,
      description: `Introducing the iPad Air 10.9-inch, the perfect blend of power and versatility in a sleek and portable design. With its stunning Liquid Retina display, this iPad offers immersive visuals with vibrant colors and sharp details. Powered by the A14 Bionic chip, it delivers impressive performance and smooth multitasking capabilities, allowing you to tackle any task with ease. The iPad Air 10.9-inch supports Apple Pencil and Magic Keyboard, enabling you to unleash your creativity and boost productivity. With advanced features like Touch ID, USB-C connectivity, and all-day battery life, this iPad is ready to accompany you throughout your day. Experience the ultimate combination of performance, style, and convenience with the iPad Air 10.9-inch.`,
      imageUrl: '/images/Ipad-Air.jpeg',
      category_id: 3,
    },
    {
      id: 14,
      name: 'Ipad Mini 8.3Inch',
      price: 1999,
      description: `Introducing the iPad mini 8.3-inch, a compact powerhouse that redefines portability. With its sleek and lightweight design, this iPad mini is perfect for on-the-go productivity and entertainment. The 8.3-inch Liquid Retina display offers stunning visuals with vivid colors and sharp details, making everything come to life. Powered by the A15 Bionic chip, it delivers impressive performance, enabling smooth multitasking and immersive gaming experiences. The iPad mini 8.3-inch supports Apple Pencil, allowing you to take notes, draw, and unleash your creativity with precision. With advanced features like Touch ID, USB-C connectivity, and all-day battery life, this iPad mini is designed to keep up with your busy lifestyle. Experience the power of an iPad in a compact form factor with the iPad mini 8.3-inch.`,
      imageUrl: '/images/Ipad-Mini.jpeg',
      category_id: 3,
    },
    {
      id: 15,
      name: 'Airpods (2nd Gen)',
      price: 249,
      description: `
      Introducing the AirPods 2nd generation, the epitome of wireless audio convenience. With their sleek and minimalist design, these earbuds provide a seamless and effortless listening experience. The AirPods 2nd gen deliver high-quality sound with rich bass and clear vocals, immersing you in your favorite music and podcasts. With the H1 chip, they offer faster and more stable wireless connectivity, ensuring a reliable connection to your devices. The convenience of "Hey Siri" voice activation allows you to control your music and make hands-free calls with ease. The AirPods 2nd gen come with a wireless charging case, offering extended battery life and hassle-free charging. Enjoy the freedom of wireless audio with the AirPods 2nd generation.`,
      imageUrl: '/images/Airpod.png',
      category_id: 4,
    },
    {
      id: 16,
      name: 'Airpods (3rd Gen)',
      price: 349,
      description: `
      Introducing the AirPods 3rd generation, the pinnacle of wireless audio technology. With their sleek and refined design, these earbuds offer a seamless and immersive listening experience. The AirPods 3rd gen deliver exceptional sound quality with enhanced bass and crisp, clear audio reproduction, taking your music, podcasts, and calls to new heights. Powered by the advanced H1 chip, they provide fast and stable wireless connectivity, ensuring a seamless connection to your devices. The redesigned shape offers a secure and comfortable fit for all-day wear. The AirPods 3rd gen feature active noise cancellation, blocking out external distractions for an immersive audio experience. With an improved battery life and the convenience of wireless charging, the AirPods 3rd generation are the ultimate companion for your on-the-go lifestyle. Elevate your audio experience with the AirPods 3rd generation and indulge in exceptional sound quality.`,
      imageUrl: '/images/Airpods-3rdGen.jpeg',
      category_id: 4,
    },
    {
      id: 17,
      name: 'Airpods Max',
      price: 979,
      description: `Introducing the AirPods Max, the epitome of premium audio excellence. With their sleek and luxurious design, these over-ear headphones deliver an immersive and high-fidelity listening experience. The AirPods Max feature custom-designed dynamic drivers that produce rich, detailed sound across a wide range of frequencies. Active Noise Cancellation technology blocks out external noise, allowing you to focus on your music or calls. The breathable mesh canopy and memory foam ear cushions provide exceptional comfort for extended listening sessions. With intuitive controls, you can easily adjust volume, change tracks, and answer calls. The AirPods Max offer seamless integration with Apple devices, providing effortless setup and automatic device switching. Experience audio like never before with the AirPods Max and elevate your music enjoyment to new heights.`,
      imageUrl: '/images/Airpods-Max.webp',
      category_id: 4,
    },
    {
      id: 18,
      name: 'Teemo',
      price: 9999,
      description: `Meet Teemo, the adorable feline companion of Jiho. With his charming grey and white fur, Teemo is a true heart-stealer. This food-motivated boy can't resist the temptation of a tasty treat, making him a joy to train and interact with. But Teemo's love for food is matched only by his love for cuddles and belly rubs. He adores snuggling up with his human, purring contentedly as he receives all the affection he craves. Teemo brings endless joy and warmth to Jiho's life, creating countless cherished moments filled with laughter and love. With his playful personality and irresistible charm, Teemo is the perfect companion for those seeking a cuddly and food-loving feline friend.`,
      imageUrl: '/images/Teemo.png',
      category_id: 5,
    },
    {
      id: 19,
      name: 'Mulan',
      price: 9999,
      description: `Meet Mulan, the fearless and independent feline companion of Jiho. As an outdoor cat, Mulan embraces her adventurous spirit and loves exploring the world around her. With her lightning-fast speed and lightweight physique, she effortlessly dashes through the neighborhood, always ready to protect her daddies from other cats or any perceived threats. Mulan's vigilant nature and unwavering loyalty make her a true guardian of her territory. While she may have her boundaries, her playful spirit and affectionate purrs show her love for Jiho. Mulan's presence adds an extra layer of security and joy to Jiho's life, making her an irreplaceable and beloved member of the family.`,
      imageUrl: '/images/Mulan.png',
      category_id: 5,
    },
    {
      id: 20,
      name: 'Doug',
      price: 9999,
      description: `Introducing Doug, the adorable Corgi and faithful companion of William. With his short legs and endearing appearance, Doug is undeniably one of the cutest dogs around. Despite his small stature, Doug possesses an abundance of energy and a playful spirit that brings joy to everyone around him. Whether it's chasing after his favorite toys or going for walks with William, Doug's enthusiasm is contagious. His loving and loyal nature make him the perfect companion for William, providing endless cuddles and unwavering companionship. With his irresistible charm and cute antics, Doug has a special place in William's heart, bringing warmth and happiness to their lives each and every day.`,
      imageUrl: '/images/Doug.png',
      category_id: 5,
    },
  ])
}
